import React from 'react'
import './globals.css'
import 'prismjs/themes/prism-tomorrow.css';
import NextContextProvider, { useNextContext } from '@/context/NextContext';
import "@uiw/codemirror-theme-abcdef"


export const metadata = {
  title: 'Learn front-end',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`m-0 p-0 w-full h-full  mx-auto overflow-x-hidden`}>
        <NextContextProvider>
          {children}
        </NextContextProvider>
      </body>
    </html>
  )
}
