import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-0 p-0 w-full h-full  mx-auto overflow-x-hidden`}>
      <div className="absolute top-0 w-full  bg-gradient-to-b from-white/20 -z-[10] to-gray-300 blur-sm"></div>
        
       
        {children}
      </body>
    </html>
  )
}
